//
//  DSGraphics.h
//  The Spectacular Sync Engine
//
//  Created by Michael Tyson on 7/01/2015.
//  Copyright (c) 2015 A Tasty Pixel. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface DSGraphics : NSObject

// Colors
+ (UIColor*)activeColor;

// Drawing Methods
+ (void)drawPauseWithFrame: (CGRect)frame;
+ (void)drawPlayWithFrame: (CGRect)frame;

@end
